name = "WMesa"
uuid = "11ef6918-d2a1-4d09-8ff3-a8f27dc47c79"
authors = ["Paulo Jabardo <pjabardo@ipt.br>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
